<?php

namespace BOS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemRepository extends EntityRepository
{
	
}
